### ISSUE TITLE
xmlParseEntityRef: no name error

### ISSUE THREAD

**Issue by bmbrands** [RichardPilbery/moodle-booktool_epubexport#1]
Awesome tool! It worked for most of the books I have one one it gave me this error when trying to open the epub in iBooks

![screen shot 2015-06-07 at 09 20 12](https://cloud.githubusercontent.com/assets/491790/8023019/a90c21c6-0cf6-11e5-8197-95c8f8a70598.png)

**Comment by RichardPilbery** [comment]
Hi Bas, Thanks for letting me know. I've not come across this error before, but have had issue with iBooks inserting a large red box complaining about a rendering error when I've inserted a YouTube video or similar, although it opened the ebook fine and rendered everything else okay. This sounds like the epub did not open at all, correct?

![screen shot 2015-06-07 at 10 06 20](https://cloud.githubusercontent.com/assets/5834254/8023281/e0572eea-0cfc-11e5-91ab-7375aa4ceb87.png)

Does your book have anything other than text, tables, or images within it?  Even better, would you be prepared to share it with me?

**Comment by bmbrands** [comment]
Hi Richard,
It looks like the issue is related to a missing image in the Book. So I guess that broke the epub. I can ask the creator of the content if it can be shared if you still want to investigate it. But I guess you rely on valid Moodle book instances without missing stuff and there is no reason your code should fix that :)
