### ISSUE TITLE
Missing language string in logs

### ISSUE THREAD

**Issue by bmbrands** [RichardPilbery/moodle-booktool_epubexport#2]
When searching which book I published using this awesome tool I saw this while in Moodle debug mode:

Invalid get_string() identifier: 'eventbookexported' or component 'booktool_epubexport'. Perhaps you are missing $string['eventbookexported'] = '';

**Comment by RichardPilbery** [comment]
Cheers Bas, It's quite correct, I'd misnamed the string as eventebookexported.  All fixed now!
